HoneyIllinix 391 MP 3: interrupt/handler.c File Reference
handler.c File Reference
#include "handler.h"
#include "vectors.h"
#include "../lib.h"
#include "../i8259.h"
#include "../driver/keyboard.h"
#include "../driver/terminal.h"
#include "../rtc.h"
Functions
void handle_timer ()
void handle_keyboard ()
void handle_rtc ()
void handle_syscall ()
void handle_exception (uint8_t vector_no)
void default_interrupt ()
Function Documentation
default_interrupt()
void default_interrupt ()
Default Interrupt Handler (for undefined IDT entries) INPUT: None. OUTPUT: None. EFFECT: Handles syscall.
Definition at line 91 of file handler.c.
References cli, printf(), and sti.
Referenced by init_idt().
{
     cli();
     printf("Undefined interrupt!\n");
     sti();
 }
handle_exception()
void handle_exception (uint8_t vector_no)
Exception handler for a given vector number. INPUT: None. OUTPUT: None. EFFECT: Handles syscall.
Definition at line 78 of file handler.c.
References printf().
{
     // TODO: Display a BSOD for the given interrupt vector
     printf("EXCEPTION\n");
     printf("Vector #%d: %s\n", vector_no, exception_messages[vector_no]);
     while(1);
 }
handle_keyboard()
void handle_keyboard ()
Keyboard handler INPUT: None. OUTPUT: None. EFFECT: Handles keyboard interrupt.
Definition at line 32 of file handler.c.
References alt_down, cli, ctrl_down, get_keyboard_input(), KB_IRQNUM, send_eoi(), sti, and terminal_handle_key().
{
     cli();
     char c = get_keyboard_input();
     terminal_handle_key(c, ctrl_down, alt_down);
     send_eoi(KB_IRQNUM);
     sti();
 }
handle_rtc()
void handle_rtc ()
RTC handler INPUT: None. OUTPUT: None. EFFECT: Handles RTC interrupt.
Definition at line 47 of file handler.c.
References cli, outb, and RTC_PORT.
                   {
     // TODO: Actually handle RTC interrupt
     // Might need an assembly wrapper for this.
     cli();
     outb(0x0C, RTC_PORT);   // select registers C
     inb(RTC_CMOS_PORT); // discard value, allow another irq to be genereate
     test_rtc_ticks_incr(); // increments rtc test tick counter if enabled
     rtc_interrupt_recieved();
     send_eoi(RTC_IRQNUM);
     sti();
 }
handle_syscall()
void handle_syscall ()
Syscall handler INPUT: None. OUTPUT: None. EFFECT: Handles syscall.
Definition at line 67 of file handler.c.
Referenced by init_idt().
                       {
     // TODO: Actually handle the syscall
     // Definitely need an assembly wrapper for this.
 }
handle_timer()
void handle_timer ()
Timer handler INPUT: None. OUTPUT: None. EFFECT: Handles timer chip interrupt.
Definition at line 17 of file handler.c.
References cli, send_eoi(), and sti.
                     {
     // TODO: Actually handle keyboard interrupt
     // Might need an assembly wrapper for this.
     cli();
     send_eoi(0);
     // printf("Timer interrupt\n");
     sti();
 }