HoneyIllinix 391 MP 3: i8259.c File Reference
i8259.c File Reference
#include "i8259.h"
#include "lib.h"
Functions
void i8259_init (void)
void enable_irq (uint32_t irq_num)
void disable_irq (uint32_t irq_num)
void send_eoi (uint32_t irq_num)
Variables
uint8_t master_mask
uint8_t slave_mask
Function Documentation
disable_irq()
void disable_irq (uint32_t irq_num)
Definition at line 72 of file i8259.c.
{
     // BEGIN CP1.4
     // REF  P#13-14 Intel 8259A PIC datasheet, OCW1
     uint8_t int_reg_value; // holds mask
     if (irq_num < 8) {                                      // if a IRQ number is for master
         int_reg_value = inb(MASTER_8259_PORT+1);            // read in current mask from master data port
         int_reg_value = int_reg_value | (0x1 << irq_num);   // set selected bit to one
         outb(int_reg_value, MASTER_8259_PORT+1);            // send it back to master data port
     }
     else if (irq_num >= 8 && irq_num < 16) {                    // if IRQ number is for slave
         int_reg_value = inb(SLAVE_8259_PORT+1);                 // read in current mask from slave data port
         int_reg_value = int_reg_value | (0x1 << (irq_num - 8));   // set selected bit to one
         outb(int_reg_value, SLAVE_8259_PORT+1);                 // send it back to slave data port
     }
     // END CP1.4
 }
enable_irq()
void enable_irq (uint32_t irq_num)
Definition at line 47 of file i8259.c.
Referenced by i8259_init(), and keyboard_init().
{
     // BEGIN CP1.4
     // REF  P#13-14 Intel 8259A PIC datasheet, OCW1
     uint8_t int_reg_value; // holds mask
     if (irq_num < 8) {                                      // if a IRQ number is for master
         int_reg_value = inb(MASTER_8259_PORT+1);            // read in current mask from master data port
         int_reg_value = int_reg_value & ~(0x1 << irq_num);  // set selected bit to zero
         outb(int_reg_value, MASTER_8259_PORT+1);            // send it back to master data port
     }
     else if (irq_num >= 8 && irq_num < 16) {                    // if IRQ number is for slave
         int_reg_value = inb(SLAVE_8259_PORT+1);                  // read in current mask from slave data port
         int_reg_value = int_reg_value & ~(0x1 << (irq_num - 8));  // set selected bit to zero, rest to one
         outb(int_reg_value, SLAVE_8259_PORT+1);                 // send it back to slave data port
     }
     // END CP1.4
 }
i8259_init()
void i8259_init (void)
Definition at line 16 of file i8259.c.
References cli, enable_irq(), ICW1, ICW2_MASTER, ICW2_SLAVE, ICW3_MASTER, ICW3_SLAVE, ICW4, MASTER_8259_PORT, outb, SLAVE_8259_PORT, and sti.
Referenced by entry().
                       {
     // BEGIN CP1.4
     // REF Notes P#41-42 PIC info
     cli(); // disables interrupts before beginning initialization
     outb(0xFF, MASTER_8259_PORT+1); // masks all interrupts on master and slave PICs
     outb(0xFF, SLAVE_8259_PORT+1);
     outb(ICW1, MASTER_8259_PORT); // Sending first initalization control words, sets PICS to edge trigger
     outb(ICW1, SLAVE_8259_PORT);  // mode, cascade mode, and to expect three more control words
     /* remaining control words are sent to PIC data ports (command port + 1) */
     outb(ICW2_MASTER, MASTER_8259_PORT+1);  // specifies high bits on interrupt vectors that are generated, to
     outb(ICW2_SLAVE, SLAVE_8259_PORT+1);    // differentiate slave and master vectors
     outb(ICW3_MASTER, MASTER_8259_PORT+1);  // tells master to expect slave inputs on IRQ2 (0x04)
     outb(ICW3_SLAVE, SLAVE_8259_PORT+1);    // tells slave it's a cascade (0x02)
     outb(ICW4, MASTER_8259_PORT+1);         // sets 8086 protocol and tells both to use
     outb(ICW4, SLAVE_8259_PORT+1);          // default end-of-interrupt signaling
     enable_irq(2);                          //enable slave PIC
     sti();                                  // renables interrupts upon completiion of PIC initialization
     // END CP1.4
 }
send_eoi()
void send_eoi (uint32_t irq_num)
Definition at line 96 of file i8259.c.
References EOI, MASTER_8259_PORT, outb, and SLAVE_8259_PORT.
Referenced by handle_keyboard(), and handle_timer().
{
     // BEGIN CP1.4
     // REF  P#13-14 Intel 8259A PIC datasheet, OCW2
     /* 0 1 1 0 0 x x x is format for a specific EOI acknowledgement,
     where lower three bits specifies the line number in decimal that
     the EOI is meant to target (0 0 0 = IRQ0, 0 1 1 = IRQ3, etc.) */
     uint8_t eoi_signal = EOI; // 0x60
     if (irq_num < 8) {
         eoi_signal = EOI | (irq_num);        // creates the proper EOI OCW2 for master
         outb(eoi_signal, MASTER_8259_PORT);  // sends it to the master PIC command port
     }
     else if (irq_num >= 8 && irq_num < 16) {               // if IRQ number is for slave
         eoi_signal = EOI | (irq_num - 8);                  // creates the proper OCW2 for the slave
         outb(eoi_signal, SLAVE_8259_PORT);                 // sends it to slave
         eoi_signal = EOI | 0x2;                            // creates the proper OCW2 for master for slave line
         outb(eoi_signal, MASTER_8259_PORT);               // sends it to master
     }
     // END CP1.4
 }
Variable Documentation
master_mask
uint8_t master_mask
Definition at line 9 of file i8259.c.
slave_mask
uint8_t slave_mask
Definition at line 10 of file i8259.c.