HoneyIllinix 391 MP 3: driver/keyboard.c File Reference
keyboard.c File Reference
#include "keyboard.h"
#include "../i8259.h"
#include "../lib.h"
Macros
#define KEY_CTRL 29
#define KEY_SHIFT_L 42
#define KEY_SHIFT_R 54
#define KEY_ALT 56
#define KEY_CAPS 58
#define KEY_UP 0x80
Functions
void keyboard_init (void)
uint8_t get_keyboard_input (void)
Variables
volatile char ctrl_down = 0
volatile char left_shift_down = 0
volatile char right_shift_down = 0
volatile char alt_down = 0
volatile char caps_down = 0
unsigned char scancode_keymap [128]
unsigned char scancode_keymap_caps [128]
Macro Definition Documentation
KEY_ALT
#define KEY_ALT 56
Definition at line 8 of file keyboard.c.
KEY_CAPS
#define KEY_CAPS 58
Definition at line 9 of file keyboard.c.
KEY_CTRL
#define KEY_CTRL 29
Definition at line 5 of file keyboard.c.
KEY_SHIFT_L
#define KEY_SHIFT_L 42
Definition at line 6 of file keyboard.c.
KEY_SHIFT_R
#define KEY_SHIFT_R 54
Definition at line 7 of file keyboard.c.
KEY_UP
#define KEY_UP 0x80
Definition at line 10 of file keyboard.c.
Function Documentation
get_keyboard_input()
uint8_t get_keyboard_input (void)
Definition at line 116 of file keyboard.c.
Referenced by handle_keyboard().
{
     uint8_t data;
     data = inb(KB_PORT); // get key press scan code
     if (data & KEY_UP) {
       // Handle release key
       data &= ~KEY_UP;
       switch (data) {
         case KEY_CTRL: ctrl_down = 0; break;
         case KEY_ALT: alt_down = 0; break;
         case KEY_SHIFT_L: left_shift_down = 0; break;
         case KEY_SHIFT_R: right_shift_down = 0; break;
       }
       return 0;
     } else {
       // Handle key down
       switch (data) {
         case KEY_CTRL: ctrl_down = 1; break;
         case KEY_ALT: alt_down = 1; break;
         case KEY_SHIFT_L: left_shift_down = 1; break;
         case KEY_SHIFT_R: right_shift_down = 1; break;
         case KEY_CAPS: caps_down = ~caps_down; break;
       }
       // If caps down and one of the shift is down, gives 0
       // If caps up and one of the shift is down, gives 1
       return (caps_down ^ (left_shift_down || right_shift_down)) ? scancode_keymap_caps[data] : scancode_keymap[data];
     }
 }
keyboard_init()
void keyboard_init (void)
Definition at line 106 of file keyboard.c.
References enable_irq(), and KB_IRQNUM.
Referenced by entry().
{
     enable_irq(KB_IRQNUM);
     return;
 }
Variable Documentation
alt_down
volatile char alt_down = 0
Definition at line 16 of file keyboard.c.
Referenced by handle_keyboard().
caps_down
volatile char caps_down = 0
Definition at line 17 of file keyboard.c.
ctrl_down
volatile char ctrl_down = 0
Definition at line 13 of file keyboard.c.
Referenced by handle_keyboard().
left_shift_down
volatile char left_shift_down = 0
Definition at line 14 of file keyboard.c.
right_shift_down
volatile char right_shift_down = 0
Definition at line 15 of file keyboard.c.
scancode_keymap
unsigned char scancode_keymap[128]
Definition at line 20 of file keyboard.c.
scancode_keymap_caps
unsigned char scancode_keymap_caps[128]
Definition at line 61 of file keyboard.c.