HoneyIllinix 391 MP 3: lib.h File Reference
lib.h File Reference
#include "types.h"
Macros
#define VIDEO 0xB8000
#define NUM_COLS 80
#define NUM_ROWS 25
#define NUM_BITS_PER_PIXEL 2
#define ATTRIB 0x7
#define ATTRIB_BLINK 0x87
#define outb(data, port)
#define outw(data, port)
#define outl(data, port)
#define cli()
#define cli_and_save(flags)
#define sti()
#define restore_flags(flags)
Functions
int32_t printf (int8_t *format,...)
void putc (uint8_t c)
int32_t puts (int8_t *s)
int8_t * itoa (uint32_t value, int8_t *buf, int32_t radix)
int8_t * strrev (int8_t *s)
uint32_t strlen (const int8_t *s)
void clear (void)
void set_cursor ()
void * memset (void *s, int32_t c, uint32_t n)
void * memset_word (void *s, int32_t c, uint32_t n)
void * memset_dword (void *s, int32_t c, uint32_t n)
void * memcpy (void *dest, const void *src, uint32_t n)
void * memmove (void *dest, const void *src, uint32_t n)
int32_t strncmp (const int8_t *s1, const int8_t *s2, uint32_t n)
int8_t * strcpy (int8_t *dest, const int8_t *src)
int8_t * strncpy (int8_t *dest, const int8_t *src, uint32_t n)
void test_interrupts (void)
int32_t bad_userspace_addr (const void *addr, int32_t len)
int32_t safe_strncpy (int8_t *dest, const int8_t *src, int32_t n)
Variables
int screen_x
int screen_y
Macro Definition Documentation
ATTRIB
#define ATTRIB 0x7
Definition at line 14 of file lib.h.
Referenced by terminal_init().
ATTRIB_BLINK
#define ATTRIB_BLINK 0x87
Definition at line 15 of file lib.h.
cli
#define cli ()
Value:
do {                                    \
    asm volatile ("cli"                 \
            :                           \
            :                           \
            : "memory", "cc"            \
    );                                  \
} while (0)
Definition at line 118 of file lib.h.
Referenced by default_interrupt(), handle_keyboard(), handle_rtc(), handle_timer(), i8259_init(), rtc_disable_period_irq(), rtc_enable_period_irq(), rtc_init(), rtc_read(), rtc_set_rate(), and rtc_write().
cli_and_save
#define cli_and_save (flags)
Value:
do {                                    \
    asm volatile ("                   \n\            pushfl                    \n\            popl %0                   \n\            cli                       \n\            "                           \
            : "=r"(flags)               \
            :                           \
            : "memory", "cc"            \
    );                                  \
} while (0)
Definition at line 130 of file lib.h.
NUM_BITS_PER_PIXEL
#define NUM_BITS_PER_PIXEL 2
Definition at line 13 of file lib.h.
Referenced by switch_terminal().
NUM_COLS
#define NUM_COLS 80
Definition at line 11 of file lib.h.
Referenced by clear(), scroll(), set_cursor(), switch_terminal(), terminal_init(), and test_interrupts().
NUM_ROWS
#define NUM_ROWS 25
Definition at line 12 of file lib.h.
Referenced by clear(), newline(), scroll(), switch_terminal(), terminal_init(), and test_interrupts().
outb
#define outb (data, port)
Value:
do {                                    \
    asm volatile ("outb %b1, (%w0)"     \
            :                           \
            : "d"(port), "a"(data)      \
            : "memory", "cc"            \
    );                                  \
} while (0)
Definition at line 88 of file lib.h.
Referenced by handle_rtc(), i8259_init(), rtc_disable_period_irq(), rtc_enable_period_irq(), rtc_init(), rtc_set_rate(), send_eoi(), and set_cursor().
outl
#define outl (data, port)
Value:
do {                                    \
    asm volatile ("outl %l1, (%w0)"     \
            :                           \
            : "d"(port), "a"(data)      \
            : "memory", "cc"            \
    );                                  \
} while (0)
Definition at line 108 of file lib.h.
outw
#define outw (data, port)
Value:
do {                                    \
    asm volatile ("outw %w1, (%w0)"     \
            :                           \
            : "d"(port), "a"(data)      \
            : "memory", "cc"            \
    );                                  \
} while (0)
Definition at line 98 of file lib.h.
restore_flags
#define restore_flags (flags)
Value:
do {                                    \
    asm volatile ("                   \n\            pushl %0                  \n\            popfl                     \n\            "                           \
            :                           \
            : "r"(flags)                \
            : "memory", "cc"            \
    );                                  \
} while (0)
Definition at line 156 of file lib.h.
sti
#define sti ()
Value:
do {                                    \
    asm volatile ("sti"                 \
            :                           \
            :                           \
            : "memory", "cc"            \
    );                                  \
} while (0)
Definition at line 144 of file lib.h.
Referenced by default_interrupt(), entry(), handle_keyboard(), handle_timer(), i8259_init(), rtc_read(), rtc_set_rate(), and rtc_write().
VIDEO
#define VIDEO 0xB8000
Definition at line 10 of file lib.h.
Referenced by switch_terminal().
Function Documentation
bad_userspace_addr()
int32_t bad_userspace_addr (const void * addr, int32_t len)
clear()
void clear (void)
Definition at line 14 of file lib.c.
References NUM_COLS, and NUM_ROWS.
Referenced by entry(), terminal_handle_key(), and terminal_init().
                  {
     int32_t i;
     for (i = 0; i < NUM_ROWS * NUM_COLS; i++) {
         *(uint8_t *)(video_mem + (i << 1)) = ' ';
         *(uint8_t *)(video_mem + (i << 1) + 1) = ATTRIB;
     }
     screen_x = 0;
     screen_y = 0;
     set_cursor();
 }
itoa()
int8_t* itoa (uint32_t value, int8_t * buf, int32_t radix)
Definition at line 258 of file lib.c.
References strrev().
Referenced by printf().
{
     static int8_t lookup[] = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
     int8_t *newbuf = buf;
     int32_t i;
     uint32_t newval = value;
     /* Special case for zero */
     if (value == 0) {
         buf[0] = '0';
         buf[1] = '\0';
         return buf;
     }
     /* Go through the number one place value at a time, and add the
      * correct digit to "newbuf".  We actually add characters to the
      * ASCII string from lowest place value to highest, which is the
      * opposite of how the number should be printed.  We'll reverse the
      * characters later. */
     while (newval > 0) {
         i = newval % radix;
         *newbuf = lookup[i];
         newbuf++;
         newval /= radix;
     }
     /* Add a terminating NULL */
     *newbuf = '\0';
     /* Reverse the string and return */
     return strrev(buf);
 }
memcpy()
void* memcpy (void * dest, const void * src, uint32_t n)
Definition at line 409 of file lib.c.
Referenced by switch_terminal().
{
     asm volatile ("                 \n\
             .memcpy_top:            \n\
             testl   %%ecx, %%ecx    \n\
             jz      .memcpy_done    \n\
             testl   $0x3, %%edi     \n\
             jz      .memcpy_aligned \n\
             movb    (%%esi), %%al   \n\
             movb    %%al, (%%edi)   \n\
             addl    $1, %%edi       \n\
             addl    $1, %%esi       \n\
             subl    $1, %%ecx       \n\
             jmp     .memcpy_top     \n\
             .memcpy_aligned:        \n\
             movw    %%ds, %%dx      \n\
             movw    %%dx, %%es      \n\
             movl    %%ecx, %%edx    \n\
             shrl    $2, %%ecx       \n\
             andl    $0x3, %%edx     \n\
             cld                     \n\
             rep     movsl           \n\
             .memcpy_bottom:         \n\
             testl   %%edx, %%edx    \n\
             jz      .memcpy_done    \n\
             movb    (%%esi), %%al   \n\
             movb    %%al, (%%edi)   \n\
             addl    $1, %%edi       \n\
             addl    $1, %%esi       \n\
             subl    $1, %%edx       \n\
             jmp     .memcpy_bottom  \n\
             .memcpy_done:           \n\
             "
             :
             : "S"(src), "D"(dest), "c"(n)
             : "eax", "edx", "memory", "cc"
     );
     return dest;
 }
memmove()
void* memmove (void * dest, const void * src, uint32_t n)
Definition at line 455 of file lib.c.
{
     asm volatile ("                             \n\
             movw    %%ds, %%dx                  \n\
             movw    %%dx, %%es                  \n\
             cld                                 \n\
             cmp     %%edi, %%esi                \n\
             jae     .memmove_go                 \n\
             leal    -1(%%esi, %%ecx), %%esi     \n\
             leal    -1(%%edi, %%ecx), %%edi     \n\
             std                                 \n\
             .memmove_go:                        \n\
             rep     movsb                       \n\
             "
             :
             : "D"(dest), "S"(src), "c"(n)
             : "edx", "memory", "cc"
     );
     return dest;
 }
memset()
void* memset (void * s, int32_t c, uint32_t n)
Definition at line 326 of file lib.c.
{
     c &= 0xFF;
     asm volatile ("                 \n\
             .memset_top:            \n\
             testl   %%ecx, %%ecx    \n\
             jz      .memset_done    \n\
             testl   $0x3, %%edi     \n\
             jz      .memset_aligned \n\
             movb    %%al, (%%edi)   \n\
             addl    $1, %%edi       \n\
             subl    $1, %%ecx       \n\
             jmp     .memset_top     \n\
             .memset_aligned:        \n\
             movw    %%ds, %%dx      \n\
             movw    %%dx, %%es      \n\
             movl    %%ecx, %%edx    \n\
             shrl    $2, %%ecx       \n\
             andl    $0x3, %%edx     \n\
             cld                     \n\
             rep     stosl           \n\
             .memset_bottom:         \n\
             testl   %%edx, %%edx    \n\
             jz      .memset_done    \n\
             movb    %%al, (%%edi)   \n\
             addl    $1, %%edi       \n\
             subl    $1, %%edx       \n\
             jmp     .memset_bottom  \n\
             .memset_done:           \n\
             "
             :
             : "a"(c << 24 | c << 16 | c << 8 | c), "D"(s), "c"(n)
             : "edx", "memory", "cc"
     );
     return s;
 }
memset_dword()
void* memset_dword (void * s, int32_t c, uint32_t n)
Definition at line 389 of file lib.c.
{
     asm volatile ("                 \n\
             movw    %%ds, %%dx      \n\
             movw    %%dx, %%es      \n\
             cld                     \n\
             rep     stosl           \n\
             "
             :
             : "a"(c), "D"(s), "c"(n)
             : "edx", "memory", "cc"
     );
     return s;
 }
memset_word()
void* memset_word (void * s, int32_t c, uint32_t n)
Definition at line 369 of file lib.c.
{
     asm volatile ("                 \n\
             movw    %%ds, %%dx      \n\
             movw    %%dx, %%es      \n\
             cld                     \n\
             rep     stosw           \n\
             "
             :
             : "a"(c), "D"(s), "c"(n)
             : "edx", "memory", "cc"
     );
     return s;
 }
printf()
int32_t printf (int8_t * format, ...)
Definition at line 94 of file lib.c.
References itoa(), putc(), puts(), and strlen().
Referenced by default_interrupt(), entry(), exception_test(), handle_exception(), initialize_memory_mp3_test(), launch_tests(), paging_tests(), rtc_test(), and terminal_test().
{
     /* Pointer to the format string */
     int8_t* buf = format;
     /* Stack pointer for the other parameters */
     int32_t* esp = (void *)&format;
     esp++;
     while (*buf != '\0') {
         switch (*buf) {
             case '%':
                 {
                     int32_t alternate = 0;
                     buf++;
 format_char_switch:
                     /* Conversion specifiers */
                     switch (*buf) {
                         /* Print a literal '%' character */
                         case '%':
                             putc('%');
                             break;
                         /* Use alternate formatting */
                         case '#':
                             alternate = 1;
                             buf++;
                             /* Yes, I know gotos are bad.  This is the
                              * most elegant and general way to do this,
                              * IMHO. */
                             goto format_char_switch;
                         /* Print a number in hexadecimal form */
                         case 'x':
{
                                 int8_t conv_buf[64];
                                 if (alternate == 0) {
                                     itoa(*((uint32_t *)esp), conv_buf, 16);
                                     puts(conv_buf);
                                 } else {
                                     int32_t starting_index;
                                     int32_t i;
                                     itoa(*((uint32_t *)esp), &conv_buf[8], 16);
                                     i = starting_index = strlen(&conv_buf[8]);
                                     while(i < 8) {
                                         conv_buf[i] = '0';
                                         i++;
                                     }
                                     puts(&conv_buf[starting_index]);
                                 }
                                 esp++;
                             }
                             break;
                         /* Print a number in unsigned int form */
                         case 'u':
{
                                 int8_t conv_buf[36];
                                 itoa(*((uint32_t *)esp), conv_buf, 10);
                                 puts(conv_buf);
                                 esp++;
                             }
                             break;
                         /* Print a number in signed int form */
                         case 'd':
{
                                 int8_t conv_buf[36];
                                 int32_t value = *((int32_t *)esp);
                                 if(value < 0) {
                                     conv_buf[0] = '-';
                                     itoa(-value, &conv_buf[1], 10);
                                 } else {
                                     itoa(value, conv_buf, 10);
                                 }
                                 puts(conv_buf);
                                 esp++;
                             }
                             break;
                         /* Print a single character */
                         case 'c':
                             putc((uint8_t) *((int32_t *)esp));
                             esp++;
                             break;
                         /* Print a NULL-terminated string */
                         case 's':
                             puts(*((int8_t **)esp));
                             esp++;
                             break;
                         default:
                             break;
                     }
                 }
                 break;
             default:
                 putc(*buf);
                 break;
         }
         buf++;
     }
     return (buf - format);
 }
putc()
void putc (uint8_t c)
Definition at line 220 of file lib.c.
References newline(), and screen_x.
Referenced by printf(), puts(), terminal_handle_key(), and terminal_write().
                      {
     // Ignore empty character
     if (!c) return;
     if (c == '\n' || c == '\r') {
         newline();
     } else if (c == '\b') {
         // Handle backspace: Erase the current character
         // If currently beginning of the line, do nothing
         if (!screen_x) return;
         // Move to the last character
         screen_x --;
         // Now erase this character
         *(uint8_t *)(video_mem + ((NUM_COLS * screen_y + screen_x) << 1)) = ' ';
         *(uint8_t *)(video_mem + ((NUM_COLS * screen_y + screen_x) << 1) + 1) = ATTRIB;
     } else {
         // If X is already at the end of the line, do newline first
         if (screen_x >= NUM_COLS - 1) newline();
         *(uint8_t *)(video_mem + ((NUM_COLS * screen_y + screen_x) << 1)) = c;
         *(uint8_t *)(video_mem + ((NUM_COLS * screen_y + screen_x) << 1) + 1) = ATTRIB;
         screen_x++;
         // We are doing this still just in case, but it shouldn't happen
         // We'll raise an exception
         if (screen_x >= NUM_COLS || screen_y >= NUM_COLS) {
             asm volatile("int $15"); // Assertion failure
             screen_x %= NUM_COLS;
             screen_y = (screen_y + (screen_x / NUM_COLS)) % NUM_ROWS;
         }
     }
     set_cursor();
 }
puts()
int32_t puts (int8_t * s)
Definition at line 207 of file lib.c.
References putc().
Referenced by printf().
{
     register int32_t index = 0;
     while (s[index] != '\0') {
         putc(s[index]);
         index++;
     }
     return index;
 }
safe_strncpy()
int32_t safe_strncpy (int8_t * dest, const int8_t * src, int32_t n)
set_cursor()
void set_cursor ()
Definition at line 30 of file lib.c.
References NUM_COLS, outb, screen_x, and screen_y.
Referenced by newline(), and switch_terminal().
                       {
     // REF https://wiki.osdev.org/Text_Mode_Cursor
     uint16_t pos = screen_y * NUM_COLS + screen_x;
     outb(0x0F, 0x3D4);
     outb((uint8_t) (pos & 0xff), 0x3D5);
     outb(0x0E, 0x3D4);
     outb((uint8_t) (pos >> 8), 0x3D5);
 }
strcpy()
int8_t* strcpy (int8_t * dest, const int8_t * src)
Definition at line 507 of file lib.c.
{
     int32_t i = 0;
     while (src[i] != '\0') {
         dest[i] = src[i];
         i++;
     }
     dest[i] = '\0';
     return dest;
 }
strlen()
uint32_t strlen (const int8_t * s)
Definition at line 313 of file lib.c.
Referenced by printf(), and strrev().
{
     register uint32_t len = 0;
     while (s[len] != '\0')
         len++;
     return len;
 }
strncmp()
int32_t strncmp (const int8_t * s1, const int8_t * s2, uint32_t n)
Definition at line 486 of file lib.c.
{
     int32_t i;
     for (i = 0; i < n; i++) {
         if ((s1[i] != s2[i]) || (s1[i] == '\0') /* || s2[i] == '\0' */) {
             /* The s2[i] == '\0' is unnecessary because of the short-circuit
              * semantics of 'if' expressions in C.  If the first expression
              * (s1[i] != s2[i]) evaluates to false, that is, if s1[i] ==
              * s2[i], then we only need to test either s1[i] or s2[i] for
              * '\0', since we know they are equal. */
             return s1[i] - s2[i];
         }
     }
     return 0;
 }
strncpy()
int8_t* strncpy (int8_t * dest, const int8_t * src, uint32_t n)
Definition at line 523 of file lib.c.
{
     int32_t i = 0;
     while (src[i] != '\0' && i < n) {
         dest[i] = src[i];
         i++;
     }
     while (i < n) {
         dest[i] = '\0';
         i++;
     }
     return dest;
 }
strrev()
int8_t* strrev (int8_t * s)
Definition at line 294 of file lib.c.
References strlen().
Referenced by itoa().
{
     register int8_t tmp;
     register int32_t beg = 0;
     register int32_t end = strlen(s) - 1;
     while (beg < end) {
         tmp = s[end];
         s[end] = s[beg];
         s[beg] = tmp;
         beg++;
         end--;
     }
     return s;
 }
test_interrupts()
void test_interrupts (void)
Definition at line 540 of file lib.c.
References NUM_COLS, and NUM_ROWS.
{
     int32_t i;
     for (i = 0; i < NUM_ROWS * NUM_COLS; i++) {
         video_mem[i << 1]++;
     }
 }
Variable Documentation
screen_x
int screen_x
Definition at line 6 of file lib.c.
Referenced by newline(), putc(), set_cursor(), and switch_terminal().
screen_y
int screen_y
Definition at line 7 of file lib.c.
Referenced by newline(), set_cursor(), and switch_terminal().