HoneyIllinix 391 MP 3: paging.c File Reference
paging.c File Reference
#include "types.h"
#include "x86_desc.h"
#include "lib.h"
#include "paging.h"
Macros
#define VIDEO 0xB8000
#define EIGHTEENBITMASK 0x3FFF
#define EIGHTEEN 18
#define TENBITMASK 0x3FF
#define TEN 10
#define PGDIRSIZE 1024
#define PGTBLSIZE 1024
#define P 0
#define RW 1
#define US 2
#define PWT 3
#define PCD 4
#define A 5
#define SIX 6
#define PS 7
#define G 8
#define TWELVEMASK 0xFFFFF000
#define TWELVE 12
#define PGBASEKBADDROFFSET 13
#define PHYSPGADDROFFSET 13
#define PGBASEMBADDROFFSET 23
#define MEMSIZE 4096
#define RESTMEMSIZE 998
#define KERNEL_LOC 4194304
#define HARDCODEPGTBL0 3758096385
#define VIDEOINDEX 0xB8
Functions
int32_t pgDir [PGDIRSIZE] __attribute__ ((aligned(MEMSIZE)))
void set_dir_tbl_zero ()
void set_bit_one (int32_t *num, char bitNum)
step 1 set up tables (Michael Gulson)
void clear_bit (int32_t *num, char bitNum)
int insert_directory_entry (int isKB, int32_t physMemAddr, int isPresent)
int initialize_memory_mp3 (void)
void set_registers ()
step 2 set registers (Mak)
void flush_tlb (void)
int initialize_memory_mp3_test ()
Macro Definition Documentation
A
#define A 5
Definition at line 130 of file paging.c.
EIGHTEEN
#define EIGHTEEN 18
Definition at line 120 of file paging.c.
EIGHTEENBITMASK
#define EIGHTEENBITMASK 0x3FFF
Definition at line 119 of file paging.c.
G
#define G 8
Definition at line 133 of file paging.c.
HARDCODEPGTBL0
#define HARDCODEPGTBL0 3758096385
Definition at line 142 of file paging.c.
KERNEL_LOC
#define KERNEL_LOC 4194304
Definition at line 141 of file paging.c.
Referenced by insert_directory_entry().
MEMSIZE
#define MEMSIZE 4096
Definition at line 139 of file paging.c.
P
#define P 0
Definition at line 125 of file paging.c.
Referenced by insert_directory_entry().
PCD
#define PCD 4
Definition at line 129 of file paging.c.
PGBASEKBADDROFFSET
#define PGBASEKBADDROFFSET 13
Definition at line 136 of file paging.c.
PGBASEMBADDROFFSET
#define PGBASEMBADDROFFSET 23
Definition at line 138 of file paging.c.
PGDIRSIZE
#define PGDIRSIZE 1024
Definition at line 123 of file paging.c.
Referenced by initialize_memory_mp3_test(), and set_dir_tbl_zero().
PGTBLSIZE
#define PGTBLSIZE 1024
Definition at line 124 of file paging.c.
PHYSPGADDROFFSET
#define PHYSPGADDROFFSET 13
Definition at line 137 of file paging.c.
PS
#define PS 7
Definition at line 132 of file paging.c.
Referenced by insert_directory_entry().
PWT
#define PWT 3
Definition at line 128 of file paging.c.
RESTMEMSIZE
#define RESTMEMSIZE 998
Definition at line 140 of file paging.c.
RW
#define RW 1
Definition at line 126 of file paging.c.
Referenced by insert_directory_entry().
SIX
#define SIX 6
Definition at line 131 of file paging.c.
TEN
#define TEN 10
Definition at line 122 of file paging.c.
TENBITMASK
#define TENBITMASK 0x3FF
Definition at line 121 of file paging.c.
TWELVE
#define TWELVE 12
Definition at line 135 of file paging.c.
TWELVEMASK
#define TWELVEMASK 0xFFFFF000
Definition at line 134 of file paging.c.
Referenced by insert_directory_entry().
US
#define US 2
Definition at line 127 of file paging.c.
VIDEO
#define VIDEO 0xB8000
Definition at line 118 of file paging.c.
Referenced by initialize_memory_mp3(), and insert_directory_entry().
VIDEOINDEX
#define VIDEOINDEX 0xB8
Definition at line 143 of file paging.c.
Referenced by insert_directory_entry().
Function Documentation
__attribute__()
int32_t pgDir [PGDIRSIZE] __attribute__ ((aligned(MEMSIZE)))
clear_bit()
void clear_bit (int32_t * num, char bitNum)
Definition at line 177 of file paging.c.
{
   *num &= ~(1UL << bitNum);
     return;
 }
flush_tlb()
void flush_tlb (void)
Definition at line 439 of file paging.c.
Referenced by initialize_memory_mp3().
                      {
     asm volatile("  \n\
     movl %%cr3, %%ecx   \n\
     movl %%ecx, %%cr3   \n\
     "
     :
     :
     :"ecx"
 );
 }
initialize_memory_mp3()
int initialize_memory_mp3 (void)
Definition at line 371 of file paging.c.
References flush_tlb(), insert_directory_entry(), set_dir_tbl_zero(), set_registers(), and VIDEO.
Referenced by entry(), and initialize_memory_mp3_test().
{
   //initialize directory entry for video memory
 // virtual_mem_packet init_mem ;
 //
 set_dir_tbl_zero();
 insert_directory_entry(0, VIDEO, 0);  //technically inputs don't matter because I hard coded
 set_registers();
 flush_tlb();
 //set_registers();
 //flush_tlb();
 //The physical mem address for video memory will be 0xB8000
 //int insert_directory_entry(int isKB, int32_t physMemAddr, int isPresent){
 //if(insert_directory_entry(1, VIDEO, 1)!=0){   return -1;}//
  //initialize directory entry for kernel memory
 //if(insert_directory_entry(0,KERNEL_SIZE , 1)!=0){return -1;}
 /*TA Peter said we dont need this */
  //initialize directory entry for rest of memory (not present)
 // int insert_directory_entry(bool isKB, int32_t physMemAddr, bool isPresent);
 return 0;
 }
initialize_memory_mp3_test()
int initialize_memory_mp3_test (void)
Definition at line 462 of file paging.c.
References initialize_memory_mp3(), PGDIRSIZE, and printf().
{
     int i ;
     if(initialize_memory_mp3()==0){
         for(i =0 ; i < PGDIRSIZE; i++ ){
             printf("i = %d \n", i);
             printf("pgDir[i] = %d \n", pgDir[i]);
             printf("pgTbl[i] = %d \n ", pgTbl[i]);
             if(pgDir[i]==0&pgTbl[i]==0){
                 break;
             }
         }
     }
     else{
         return -1;
     }
     return 0;
 }
insert_directory_entry()
int insert_directory_entry (int isKB, int32_t physMemAddr, int isPresent)
Definition at line 188 of file paging.c.
References KERNEL_LOC, P, PS, RW, set_bit_one(), TWELVEMASK, VIDEO, and VIDEOINDEX.
Referenced by initialize_memory_mp3().
{
   int32_t physMemAddrTop2, physMemAddrBottom18;
   int32_t pgTblBitmask;
   //int32_t virtualAddress;
   int32_t newPgDirEntry, newPgTblEntry;
   /*pgDir[0] =0;
   pgDir[1] =1;
   pgDir[2] =1024;
   pgDir[3] = 129;
   pgTbl[0] =2;
   pgTbl[1] = HARDCODEPGTBL0;*/
   //initialize visual memory
   /*page-directory entry (4 KB)
       31                   13 12   9 8  7 6 5  4  3   2  1 0
       |      page Base Address|Avail|G|PS|0|A|PCD|PWT|US|RW|P|  */
   //set P(bit0) to isPresent
   // the top 18 bits should point to pgTbl
   newPgDirEntry = (int32_t)pgTbl & TWELVEMASK;
   set_bit_one(&newPgDirEntry, P);
   set_bit_one(&newPgDirEntry, RW);
   //set PS(bit7) to 0 for KB
   //clear_bit(&newPgDirEntry, PS); //already zero
   //clear bit 6
   //clear_bit(&newPgDirEntry2, SIX);
   pgDir[0] = newPgDirEntry;
   /*    page-directory entry (4 MB)
     |--32 bits--|
     31               22 21     13 12  9 8  7 6 5  4   3   2  1 0
     |page Base Address| Reserved |Avail|G|PS|0|A|PCD|PWT|US|RW|P|*/
   newPgDirEntry = (KERNEL_LOC & TWELVEMASK);
   set_bit_one(&newPgDirEntry, P);
   set_bit_one(&newPgDirEntry, RW);
   //set PS(bit7) to 1 for MB
   //set RW
   set_bit_one(&newPgDirEntry, PS);
   pgDir[1] = newPgDirEntry;
   /*    page Table entry (4 KB page)
       |--32 bits--|
       31                    13 12    9 8  7 6 5  4  3  2  1 0
       |      page Base Address|Avail|G|PS|0|A|PCD|PWT|US|RW|P|    */
   newPgTblEntry = (VIDEO & TWELVEMASK);
   set_bit_one(&newPgTblEntry, P);
   set_bit_one(&newPgTblEntry, RW);
     //set RW
   //set PS(bit7) to 1 for MB
   //set_bit_one(&newPgDirEntry, PS);
   pgTbl[VIDEOINDEX] = newPgTblEntry;
 }
set_bit_one()
void set_bit_one (int32_t * num, char bitNum)
step 1 set up tables (Michael Gulson)
Definition at line 172 of file paging.c.
Referenced by insert_directory_entry().
{
   *num |= 1UL << bitNum;
   return;
 }
set_dir_tbl_zero()
void set_dir_tbl_zero ()
Definition at line 159 of file paging.c.
References PGDIRSIZE.
Referenced by initialize_memory_mp3().
{
   int i;
   for(i=0; i < PGDIRSIZE; i++){
     pgDir[i] = 0;
   }
   for(i=0; i < PGDIRSIZE; i++){
     pgTbl[i] = 0;
   }
 }
set_registers()
void set_registers (void)
step 2 set registers (Mak)
Definition at line 418 of file paging.c.
Referenced by initialize_memory_mp3().
                     {
 asm volatile("  \n\
     movl %0, %%ecx  \n\
     movl %%ecx, %%cr3   \n\
     movl %%cr4, %%ecx   \n\
     orl $0x00000010, %%ecx  \n\
     movl %%ecx , %%cr4  \n\
     movl %%cr0, %%ecx   \n\
     orl $0x80000001, %%ecx  \n\
     movl %%ecx, %%cr0   \n\
     "
     :
     : "r"(pgDir)
     :"ecx"
     );
 }