HoneyIllinix 391 MP 3: paging.h File Reference
paging.h File Reference
Functions
void set_bit_one (int32_t *num, char bitNum)
step 1 set up tables (Michael Gulson)
void clear_bit (int32_t *num, char bitNum)
int insert_directory_entry (int isKB, int32_t physMemAddr, int isPresent)
int initialize_memory_mp3 (void)
Function Documentation
clear_bit()
void clear_bit (int32_t * num, char bitNum)
Definition at line 177 of file paging.c.
{
   *num &= ~(1UL << bitNum);
     return;
 }
initialize_memory_mp3()
int initialize_memory_mp3 (void)
Definition at line 371 of file paging.c.
References flush_tlb(), insert_directory_entry(), set_dir_tbl_zero(), set_registers(), and VIDEO.
Referenced by entry(), and initialize_memory_mp3_test().
{
   //initialize directory entry for video memory
 // virtual_mem_packet init_mem ;
 //
 set_dir_tbl_zero();
 insert_directory_entry(0, VIDEO, 0);  //technically inputs don't matter because I hard coded
 set_registers();
 flush_tlb();
 //set_registers();
 //flush_tlb();
 //The physical mem address for video memory will be 0xB8000
 //int insert_directory_entry(int isKB, int32_t physMemAddr, int isPresent){
 //if(insert_directory_entry(1, VIDEO, 1)!=0){   return -1;}//
  //initialize directory entry for kernel memory
 //if(insert_directory_entry(0,KERNEL_SIZE , 1)!=0){return -1;}
 /*TA Peter said we dont need this */
  //initialize directory entry for rest of memory (not present)
 // int insert_directory_entry(bool isKB, int32_t physMemAddr, bool isPresent);
 return 0;
 }
insert_directory_entry()
int insert_directory_entry (int isKB, int32_t physMemAddr, int isPresent)
Definition at line 188 of file paging.c.
References KERNEL_LOC, P, PS, RW, set_bit_one(), TWELVEMASK, VIDEO, and VIDEOINDEX.
Referenced by initialize_memory_mp3().
{
   int32_t physMemAddrTop2, physMemAddrBottom18;
   int32_t pgTblBitmask;
   //int32_t virtualAddress;
   int32_t newPgDirEntry, newPgTblEntry;
   /*pgDir[0] =0;
   pgDir[1] =1;
   pgDir[2] =1024;
   pgDir[3] = 129;
   pgTbl[0] =2;
   pgTbl[1] = HARDCODEPGTBL0;*/
   //initialize visual memory
   /*page-directory entry (4 KB)
       31                   13 12   9 8  7 6 5  4  3   2  1 0
       |      page Base Address|Avail|G|PS|0|A|PCD|PWT|US|RW|P|  */
   //set P(bit0) to isPresent
   // the top 18 bits should point to pgTbl
   newPgDirEntry = (int32_t)pgTbl & TWELVEMASK;
   set_bit_one(&newPgDirEntry, P);
   set_bit_one(&newPgDirEntry, RW);
   //set PS(bit7) to 0 for KB
   //clear_bit(&newPgDirEntry, PS); //already zero
   //clear bit 6
   //clear_bit(&newPgDirEntry2, SIX);
   pgDir[0] = newPgDirEntry;
   /*    page-directory entry (4 MB)
     |--32 bits--|
     31               22 21     13 12  9 8  7 6 5  4   3   2  1 0
     |page Base Address| Reserved |Avail|G|PS|0|A|PCD|PWT|US|RW|P|*/
   newPgDirEntry = (KERNEL_LOC & TWELVEMASK);
   set_bit_one(&newPgDirEntry, P);
   set_bit_one(&newPgDirEntry, RW);
   //set PS(bit7) to 1 for MB
   //set RW
   set_bit_one(&newPgDirEntry, PS);
   pgDir[1] = newPgDirEntry;
   /*    page Table entry (4 KB page)
       |--32 bits--|
       31                    13 12    9 8  7 6 5  4  3  2  1 0
       |      page Base Address|Avail|G|PS|0|A|PCD|PWT|US|RW|P|    */
   newPgTblEntry = (VIDEO & TWELVEMASK);
   set_bit_one(&newPgTblEntry, P);
   set_bit_one(&newPgTblEntry, RW);
     //set RW
   //set PS(bit7) to 1 for MB
   //set_bit_one(&newPgDirEntry, PS);
   pgTbl[VIDEOINDEX] = newPgTblEntry;
 }
set_bit_one()
void set_bit_one (int32_t * num, char bitNum)
step 1 set up tables (Michael Gulson)
Definition at line 172 of file paging.c.
Referenced by insert_directory_entry().
{
   *num |= 1UL << bitNum;
   return;
 }