HoneyIllinix 391 MP 3: rtc.c File Reference
rtc.c File Reference
#include "rtc.h"
#include "i8259.h"
#include "lib.h"
Functions
void rtc_init (void)
void rtc_enable_period_irq (void)
void rtc_disable_period_irq (void)
int rtc_set_rate (uint16_t rate)
void rtc_interrupt_recieved (void)
int32_t rtc_open (const uint8_t *filename)
int32_t rtc_read (int32_t fd, void *buf, int32_t nbytes)
int32_t rtc_write (int32_t fd, const void *buf, int32_t nbytes)
int32_t rtc_close (int32_t fd)
void test_rtc_enable (void)
void test_rtc_disable (void)
void test_rtc_ticks_incr (void)
uint32_t test_rtc_get_ticks (void)
Variables
int test_flag
volatile uint8_t interrupt_recieved
const uint8_t RATE_TABLE [15]
Function Documentation
rtc_close()
int32_t rtc_close (int32_t fd)
Definition at line 167 of file rtc.c.
Referenced by rtc_test().
{
     return 0;
 }
rtc_disable_period_irq()
void rtc_disable_period_irq (void)
Definition at line 74 of file rtc.c.
References cli, outb, RTC_B_REG, and RTC_PORT.
{
     cli();          // disable interrupts
     /* setting RTC B register */
     outb(RTC_B_REG, RTC_PORT);
     unsigned char b_old = inb(RTC_CMOS_PORT);
     outb(b_old & 0xBF, RTC_CMOS_PORT); // Sets PIE bit to zero (disables periodic interrupts)
     sti();
 }
rtc_enable_period_irq()
void rtc_enable_period_irq (void)
Definition at line 59 of file rtc.c.
References cli, outb, RTC_B_REG, and RTC_PORT.
{
     cli();          // disable interrupts
     /* setting RTC B register */
     outb(RTC_B_REG, RTC_PORT);
     unsigned char b_old = inb(RTC_CMOS_PORT);
     outb(b_old | 0x40, RTC_CMOS_PORT); // Sets PIE bit to one (enables periodic interrupts)
     sti();
 }
rtc_init()
void rtc_init (void)
Definition at line 34 of file rtc.c.
References cli, outb, RTC_A_REG, RTC_PORT, and test_flag.
Referenced by entry().
                     {
     // REF OSDev https://wiki.osdev.org/RTC, Dallas Semiconductor DS12887 Real Time Clock datasheet
     cli();
     test_flag = 0; //turns off testing ticks
     /* setting RTC A register */
     outb(RTC_A_REG, RTC_PORT);
     unsigned char a_old = inb(RTC_CMOS_PORT);
     outb((0x80 & a_old) | 0x2F, RTC_CMOS_PORT); // setting DV2-0 to 010 to turn on oscillator, clears all other bits besides UIP bit
     /* setting RTC B register */
     outb(RTC_B_REG, RTC_PORT);
     unsigned char b_old = inb(RTC_CMOS_PORT);
     outb((0x0F & b_old) | 0x40, RTC_CMOS_PORT); // Sets PIE bit to one, enables square wave, binary calendar data, 24 hour mode, and daylight savings
     enable_irq(RTC_IRQNUM); //enables the RTC irq line on the PIC
     sti();
 }
rtc_interrupt_recieved()
void rtc_interrupt_recieved (void)
Definition at line 116 of file rtc.c.
References interrupt_recieved.
{
     interrupt_recieved = 1;
     //doesnt need cli/sti because is only called from rtc handler which is already protected.
 }
rtc_open()
int32_t rtc_open (const uint8_t * filename)
Definition at line 125 of file rtc.c.
References rtc_set_rate().
Referenced by rtc_test().
{
     return rtc_set_rate(2);
 }
rtc_read()
int32_t rtc_read (int32_t fd, void * buf, int32_t nbytes)
Definition at line 136 of file rtc.c.
References cli, interrupt_recieved, and sti.
Referenced by rtc_test().
{
     cli();
     interrupt_recieved = 0;
     sti();
     while(1) { // waits until a single rtc interrupt has been recieved
             if (interrupt_recieved) {break;}
     }
     return 0;
 }
rtc_set_rate()
int rtc_set_rate (uint16_t rate)
Definition at line 89 of file rtc.c.
References cli, outb, RATE_TABLE, RTC_A_REG, RTC_CMOS_PORT, RTC_PORT, and sti.
Referenced by rtc_open(), and rtc_write().
{
     cli();
     uint8_t rate_code = 0xFF;
     int power = 0;
     uint16_t bitmask = 0x2;
     if ((rate == 0)) {return -1;} //if rate is zero, return error
     while ((bitmask & rate) == 0) {
         power++;
         bitmask = bitmask << 1;
     }
     if ((rate & (~bitmask))) {return -1;} //if a non power of two, return error
     rate_code = RATE_TABLE[power]; //get corrosponding rate code from our table
     outb(RTC_A_REG, RTC_PORT); //swtich to rtc A register
     outb(rate_code | 0x40, RTC_CMOS_PORT); // Sets rate using our rate code
     sti();
     return 0; // return success
 }
rtc_write()
int32_t rtc_write (int32_t fd, const void * buf, int32_t nbytes)
Definition at line 153 of file rtc.c.
References cli, rtc_set_rate(), and sti.
Referenced by rtc_test().
{
     cli();
     if (nbytes != 4 || buf == 0) {return -1;} // should only accept a 4 byte arg and non null pointer
     int32_t rate = *((const int32_t*)buf); // get the 4 byte arg from provided pointer
     if (rate > 1024) {return -1;} // user calls are restricted to 1024Hz
     if (rtc_set_rate(rate) == 0) {return 4;} // if success, return 4
     sti();
     return -1; //else return error
 }
test_rtc_disable()
void test_rtc_disable (void)
Definition at line 198 of file rtc.c.
References test_flag.
{
     test_flag = 0; //turns off testing ticks
     test_ticks = 0; // sets test tick to zero
 }
test_rtc_enable()
void test_rtc_enable (void)
Definition at line 189 of file rtc.c.
References test_flag.
{
     test_flag = 1; //turns on testing ticks
     test_ticks = 0; // sets test tick to zero
 }
test_rtc_get_ticks()
uint32_t test_rtc_get_ticks (void)
Definition at line 215 of file rtc.c.
{
     return test_ticks;
 }
test_rtc_ticks_incr()
void test_rtc_ticks_incr (void)
Definition at line 207 of file rtc.c.
{
     if ((test_ticks < 0xFFFFFFFF) && test_flag) {test_ticks++;}
 }
Variable Documentation
interrupt_recieved
volatile uint8_t interrupt_recieved
Definition at line 8 of file rtc.c.
Referenced by rtc_interrupt_recieved(), and rtc_read().
RATE_TABLE
const uint8_t RATE_TABLE[15]
Initial value:
= {0x0F,
                                0x0E,
                                0x0D,
                                0x0C,
                                0x0B,
                                0x0A,
                                0x09,
                                0x08,
                                0x07,
                                0x06,
                                0x05,
                                0x04,
                                0x03,
                                0x02,
                                0x01
                               }
Definition at line 11 of file rtc.c.
Referenced by rtc_set_rate().
test_flag
int test_flag
Definition at line 7 of file rtc.c.
Referenced by rtc_init(), test_rtc_disable(), and test_rtc_enable().