HoneyIllinix 391 MP 3: interrupt/table.c File Reference
table.c File Reference
#include "table.h"
#include "../types.h"
#include "handler.h"
#include "vectors.h"
#include "../x86_desc.h"
Functions
void init_idt ()
Function Documentation
init_idt()
void init_idt (void)
Initializes the IDT Table.
INPUT: none OUTPUT: none SIDE EFFECT: Populates the IDT Table.
Definition at line 36 of file table.c.
References default_interrupt(), idt_desc_t::dpl, EXC_ALIGNMENT_FAULT, EXC_ASSERTION_FAILURE, EXC_BOUND, EXC_BREAKPOINT, EXC_DEVICE_NOT_AVAIL, EXC_DIVIDE, EXC_DOUBLE_FAULT, EXC_GP_FAULT, EXC_INVALID_OP, EXC_INVALID_TSS, EXC_MACHINE_ABORT, EXC_MATH_FAULT, EXC_NMI, EXC_OVERFLOW, EXC_PAGE_FAULT, EXC_SEG_NOT_PRESENT, EXC_STACK_SEGFAULT, HANDLE_EXC_FUNCTION_NAME, handle_syscall(), idt, idt_desc_ptr, KERNEL_CS, keyboard_isr(), lidt, NUM_VEC, idt_desc_t::present, idt_desc_t::reserved1, idt_desc_t::reserved2, idt_desc_t::reserved3, idt_desc_t::reserved4, rtc_isr(), idt_desc_t::seg_selector, SET_IDT_ENTRY, idt_desc_t::size, timer_isr(), TOTAL_EXC, VEC_KEYBOARD, VEC_RTC, VEC_SYSCALL, and VEC_TIMER.
                 {
     int i;
     for (i = 0; i < NUM_VEC; i++) {
         /* Setup Checklist:
          * - seg_selector: KERNEL_CS
          * - Reserved 4 = 0
          * - Reserved123 = 110 for INT, 111 for EXC
          * - Size = 1
          * - dpl = 0, unless syscall = 3 (Call from user)
          * - present = 1
          * - Offsets no change
          */
         idt[i].seg_selector = KERNEL_CS;
         idt[i].reserved4 = 0;
         idt[i].reserved3 = (i < TOTAL_EXC);
         idt[i].reserved2 = 1;
         idt[i].reserved1 = 1;
         idt[i].size = 1;
         idt[i].dpl = (i == VEC_SYSCALL) ? 3 : 0;
         idt[i].present = 1;
         SET_IDT_ENTRY(idt[i], default_interrupt);
     }
     // Set IDT for Handlers
     SET_IDT_ENTRY(idt[VEC_SYSCALL], handle_syscall);
     SET_IDT_ENTRY(idt[VEC_TIMER], timer_isr);
     SET_IDT_ENTRY(idt[VEC_KEYBOARD], keyboard_isr);
     SET_IDT_ENTRY(idt[VEC_RTC], rtc_isr);
     // Set IDT for Exception Handlers
     // No handler for reserved exc.
     SET_IDT_ENTRY(idt[EXC_DIVIDE], HANDLE_EXC_FUNCTION_NAME(EXC_DIVIDE));
     SET_IDT_ENTRY(idt[EXC_NMI], HANDLE_EXC_FUNCTION_NAME(EXC_NMI));
     SET_IDT_ENTRY(idt[EXC_BREAKPOINT], HANDLE_EXC_FUNCTION_NAME(EXC_BREAKPOINT));
     SET_IDT_ENTRY(idt[EXC_OVERFLOW], HANDLE_EXC_FUNCTION_NAME(EXC_OVERFLOW));
     SET_IDT_ENTRY(idt[EXC_BOUND], HANDLE_EXC_FUNCTION_NAME(EXC_BOUND));
     SET_IDT_ENTRY(idt[EXC_INVALID_OP], HANDLE_EXC_FUNCTION_NAME(EXC_INVALID_OP));
     SET_IDT_ENTRY(idt[EXC_DEVICE_NOT_AVAIL], HANDLE_EXC_FUNCTION_NAME(EXC_DEVICE_NOT_AVAIL));
     SET_IDT_ENTRY(idt[EXC_DOUBLE_FAULT], HANDLE_EXC_FUNCTION_NAME(EXC_DOUBLE_FAULT));
     SET_IDT_ENTRY(idt[EXC_INVALID_TSS], HANDLE_EXC_FUNCTION_NAME(EXC_INVALID_TSS));
     SET_IDT_ENTRY(idt[EXC_SEG_NOT_PRESENT], HANDLE_EXC_FUNCTION_NAME(EXC_SEG_NOT_PRESENT));
     SET_IDT_ENTRY(idt[EXC_STACK_SEGFAULT], HANDLE_EXC_FUNCTION_NAME(EXC_STACK_SEGFAULT));
     SET_IDT_ENTRY(idt[EXC_GP_FAULT], HANDLE_EXC_FUNCTION_NAME(EXC_GP_FAULT));
     SET_IDT_ENTRY(idt[EXC_PAGE_FAULT], HANDLE_EXC_FUNCTION_NAME(EXC_PAGE_FAULT));
     SET_IDT_ENTRY(idt[EXC_ASSERTION_FAILURE], HANDLE_EXC_FUNCTION_NAME(EXC_ASSERTION_FAILURE));
     SET_IDT_ENTRY(idt[EXC_MATH_FAULT], HANDLE_EXC_FUNCTION_NAME(EXC_MATH_FAULT));
     SET_IDT_ENTRY(idt[EXC_ALIGNMENT_FAULT], HANDLE_EXC_FUNCTION_NAME(EXC_ALIGNMENT_FAULT));
     SET_IDT_ENTRY(idt[EXC_MACHINE_ABORT], HANDLE_EXC_FUNCTION_NAME(EXC_MACHINE_ABORT));
     // Final step: Load the IDT
     lidt(idt_desc_ptr);
 }