HoneyIllinix 391 MP 3: driver/terminal.c File Reference
terminal.c File Reference
#include "terminal.h"
#include "keyboard.h"
#include "../lib.h"
Functions
int32_t terminal_open ()
int32_t terminal_read (void *buf, int32_t nbytes)
int32_t terminal_write (const void *buf, int32_t nbytes)
int32_t terminal_close ()
void terminal_init ()
void switch_terminal (uint8_t target, uint8_t backup_current)
void terminal_advance_buffer (terminal_t *term, char ch)
void terminal_handle_key (uint8_t key, uint8_t ctrl, uint8_t alt)
Variables
terminal_t terminals [NUM_TERMINALS]
int current_terminal_idx = 0
Function Documentation
switch_terminal()
void switch_terminal (uint8_t target, uint8_t backup_current)
Definition at line 105 of file terminal.c.
References current_terminal_idx, terminal_t::cursor_x, terminal_t::cursor_y, memcpy(), NUM_BITS_PER_PIXEL, NUM_COLS, NUM_ROWS, screen_x, screen_y, set_cursor(), VIDEO, and terminal_t::video_buffer.
Referenced by terminal_handle_key(), and terminal_init().
{
     // Don't do this if asking to switch to the same terminal
     if (backup_current && target == current_terminal_idx) return;
     if (backup_current) {
         terminal_t* old_term = &(terminals[current_terminal_idx]);
         memcpy(
             old_term->video_buffer,
             (char*) VIDEO,
             NUM_COLS * NUM_ROWS * NUM_BITS_PER_PIXEL
             );
         old_term->cursor_x = screen_x;
         old_term->cursor_y = screen_y;
     }
     // Switch to current terminal
     current_terminal_idx = target;
     terminal_t* new_term = &(terminals[target]);
     memcpy(
         (char*) VIDEO,
         new_term->video_buffer,
         NUM_COLS * NUM_ROWS * NUM_BITS_PER_PIXEL
         );
     screen_x = new_term->cursor_x;
     screen_y = new_term->cursor_y;
     set_cursor();
 }
terminal_advance_buffer()
void terminal_advance_buffer (terminal_t * term, char ch)
Definition at line 137 of file terminal.c.
References terminal_t::buffer_pos, terminal_t::input_buffer, terminal_t::read_complete, and SIZE_INPUT_BUFFER.
Referenced by terminal_handle_key().
{
     // CASE 1: If the buffer is complete, more keystrokes can screw it
     if (term->read_complete) {
         term->input_buffer[0] = 0; // Clear the string
         term->read_complete = 0; // Reset the buffer
         term->buffer_pos = 0;
     }
     // CASE 2: Only add to buffer if input buffer is not full
     if (term->buffer_pos < SIZE_INPUT_BUFFER) {
         term->input_buffer[term->buffer_pos] = ch;
         term->buffer_pos ++;
     }
     // CASE 3: If the current char is newline, make it complete
     if (ch == '\n') term->read_complete = 1;
 }
terminal_close()
int32_t terminal_close ()
Definition at line 67 of file terminal.c.
{
     return 0;
 }
terminal_handle_key()
void terminal_handle_key (uint8_t key, uint8_t ctrl, uint8_t alt)
Definition at line 162 of file terminal.c.
References clear(), current_terminal_idx, KEY_ACCEPTED_MAX, KEY_ACCEPTED_MIN, KEY_FN, NUM_TERMINALS, putc(), switch_terminal(), and terminal_advance_buffer().
Referenced by handle_keyboard().
{
     // This is the current terminal
     terminal_t* cur_term = &(terminals[current_terminal_idx]);
     // BEGIN CP2.1
     // Case 1: Ctrl+L: Clear screen and exit
     if (ctrl) {
         switch(key) {
             case 'l': clear(); break;
             case 'L': clear(); break;
         }
         return;
     }
     if (alt) {
         // BEGIN CP5.1
         // Warning: Terminal switching does not work on the Mac.
         // Hotkeys will invoke MacOS system config utils.
         if (key >= KEY_FN && key < KEY_FN + NUM_TERMINALS) {
             // Switch terminal!!
             switch_terminal(key - KEY_FN, 1);
         }
         // END CP5.1
         return;
     }
     // Default case: Regular character, store this thing
     if (key >= KEY_ACCEPTED_MIN && key <= KEY_ACCEPTED_MAX) {
         putc(key);
         terminal_advance_buffer(cur_term, key);
     }
     // END CP2.1
 }
terminal_init()
void terminal_init ()
Definition at line 76 of file terminal.c.
References ATTRIB, terminal_t::buffer_pos, clear(), current_terminal_idx, terminal_t::cursor_x, terminal_t::cursor_y, NUM_COLS, NUM_ROWS, NUM_TERMINALS, terminal_t::read_complete, SIZE_INPUT_BUFFER, switch_terminal(), and terminal_t::video_buffer.
Referenced by entry().
                      {
     int i;
     for (i = 0; i < NUM_TERMINALS; i++) {
         // Initialize the buffers
         int j;
         for (j = 0; j < NUM_COLS * NUM_ROWS; j++) {
             terminals[i].video_buffer[j << 1] = ' ';
             terminals[i].video_buffer[(j << 1) + 1] = ATTRIB;
         }
         for (j = 0; j < SIZE_INPUT_BUFFER; j++)
             terminals[i].input_buffer[j] = 0;
         // Initialize the states
         terminals[i].buffer_pos = 0; // Resets the buffer write head
         terminals[i].read_complete = 0; // Resets the completion flag
         // Initialize the cursor
         terminals[i].cursor_x = 0;
         terminals[i].cursor_y = 0;
     }
     current_terminal_idx = 0; // Set first terminal active
     clear();
     switch_terminal(0, 0);
 }
terminal_open()
int32_t terminal_open ()
Definition at line 15 of file terminal.c.
{
     return 0;
 }
terminal_read()
int32_t terminal_read (void * buf, int32_t nbytes)
Definition at line 25 of file terminal.c.
References terminal_t::buffer_pos, current_terminal_idx, terminal_t::input_buffer, and terminal_t::read_complete.
Referenced by terminal_test().
{
     terminal_t* cur_term = &(terminals[current_terminal_idx]);
     int i;
     char *charbuf = (char*)buf;
     // Now we wait for the terminal to complete a line of input
     while(!cur_term->read_complete);
     // If asking for more than we have, we truncate it
     if (nbytes >= cur_term->buffer_pos) nbytes = cur_term->buffer_pos;
     // We could have used strncpy but we want a length here..
     // So reinventing the wheel.
     // Also this is a contingency plan if str is corrupted..
     for (i = 0; i < nbytes; i++)
         charbuf[i] = cur_term->input_buffer[i];
     // Wrapup: Clear the terminal buffer
     cur_term->read_complete = 0;
     cur_term->buffer_pos = 0;
     cur_term->input_buffer[0] = 0;
     return i;
 }
terminal_write()
int32_t terminal_write (const void * buf, int32_t nbytes)
Definition at line 51 of file terminal.c.
References putc().
Referenced by terminal_test().
{
     int i;
     char *charbuf = (char*)buf;
     for (i = 0; i < nbytes; i++) {
         // String ends? I'll just end.
         if (!charbuf[i]) break;
         putc(charbuf[i]);
     }
     return i; // Number of bytes written
 }
Variable Documentation
current_terminal_idx
int current_terminal_idx = 0
Definition at line 6 of file terminal.c.
Referenced by switch_terminal(), terminal_handle_key(), terminal_init(), and terminal_read().
terminals
terminal_t terminals[NUM_TERMINALS]
Definition at line 5 of file terminal.c.