HoneyIllinix 391 MP 3: tests.c File Reference
tests.c File Reference
#include "tests.h"
#include "x86_desc.h"
#include "rtc.h"
#include "lib.h"
#include "driver/terminal.h"
Macros
#define PASS 1
#define FAIL 0
#define TEST_HEADER printf("[TEST %s] Running %s at %s:%d\n", __FUNCTION__, __FUNCTION__, __FILE__, __LINE__)
#define TEST_OUTPUT(name, result) printf("[TEST %s] Result = %s\n", name, (result) ? "PASS" : "FAIL");
#define TEST_STR_LENGTH 20
Functions
int idt_test ()
int rtc_test ()
int terminal_test ()
int exception_test ()
int paging_tests ()
void launch_tests ()
Macro Definition Documentation
FAIL
#define FAIL 0
Definition at line 8 of file tests.c.
Referenced by rtc_test().
PASS
#define PASS 1
Definition at line 7 of file tests.c.
Referenced by exception_test(), idt_test(), paging_tests(), rtc_test(), and terminal_test().
TEST_HEADER
#define TEST_HEADER printf("[TEST %s] Running %s at %s:%d\n", __FUNCTION__, __FUNCTION__, __FILE__, __LINE__)
Definition at line 11 of file tests.c.
Referenced by exception_test(), idt_test(), paging_tests(), rtc_test(), and terminal_test().
TEST_OUTPUT
#define TEST_OUTPUT (name, result) printf("[TEST %s] Result = %s\n", name, (result) ? "PASS" : "FAIL");
Definition at line 13 of file tests.c.
Referenced by launch_tests().
TEST_STR_LENGTH
#define TEST_STR_LENGTH 20
Definition at line 16 of file tests.c.
Referenced by terminal_test().
Function Documentation
exception_test()
int exception_test ()
Definition at line 155 of file tests.c.
References PASS, printf(), and TEST_HEADER.
Referenced by launch_tests().
                     {
     TEST_HEADER;
     int result = PASS;
     printf("Dividing by zero...\n");
     asm volatile ("                           \n\
             mov    $0, %edx                   \n\
             mov    $5, %eax                   \n\
             mov    $0, %ecx                   \n\
             div    %ecx                       \n\
     ");
     return result; //if returns then this was a fail
 }
idt_test()
int idt_test ()
Definition at line 36 of file tests.c.
References idt, NULL, NUM_VEC, offset_15_00, offset_31_16, PASS, and TEST_HEADER.
Referenced by launch_tests().
               {
     TEST_HEADER;
     int i;
     int result = PASS;
     for (i = 0; i < NUM_VEC; ++i){
         if ((idt[i].offset_15_00 == NULL) &&
             (idt[i].offset_31_16 == NULL)){
             assertion_failure();
             result = FAIL;
         }
     }
     // Print sample IDT entries: Exception, Keyboard, RTC, Syscall
     const int print_entries[] = {0, 0x21, 0x28, 0x80};
     for (i = 0; i < 4; i++) {
         printf(
             "IDT#%d > R4321=%d%d%d%d, Size=%d, DPL=%d\n",
             print_entries[i],
             idt[print_entries[i]].reserved4,
             idt[print_entries[i]].reserved3,
             idt[print_entries[i]].reserved2,
             idt[print_entries[i]].reserved1,
             idt[print_entries[i]].size,
             idt[print_entries[i]].dpl
             );
     }
     return result;
 }
launch_tests()
void launch_tests ()
Definition at line 205 of file tests.c.
References exception_test(), idt_test(), paging_tests(), printf(), rtc_test(), terminal_test(), and TEST_OUTPUT.
Referenced by entry().
                    {
     printf("### RUNNING TEST SUITE ###\n");
     printf("Beginning checkpoint 1 tests...\n");
     TEST_OUTPUT("idt_test", idt_test());
     TEST_OUTPUT("rtc_test", rtc_test());
     TEST_OUTPUT("terminal_test", terminal_test());
     TEST_OUTPUT("paging_tests", paging_tests());  // this is going to crash machine, put any tests before this
     TEST_OUTPUT("exception_test", exception_test()); // this is going to crash machine, put any tests before this
     printf("checkpoint 1 tests done.\n");
 }
paging_tests()
int paging_tests ()
Definition at line 181 of file tests.c.
References PASS, printf(), and TEST_HEADER.
Referenced by launch_tests().
                   {
     TEST_HEADER;
     int temp;
     // kernel space paging test
     printf("accessing kernel memory\n");
     temp = *(int*)(0x600000);
     // video memory paging test
     printf("accessing video memory\n");
     temp = *(int*)(0xB8500);
     // should result in a segfault
     printf("accessing not present memory\n");
     printf("should segfault \n");
     temp = *(int*)(0x00000);
     //SHOULD SEGFAULT!!!!!
     return PASS;
 }
rtc_test()
int rtc_test ()
Definition at line 75 of file tests.c.
References FAIL, PASS, printf(), rtc_close(), rtc_open(), rtc_read(), rtc_write(), and TEST_HEADER.
Referenced by launch_tests().
               {
     TEST_HEADER;
     int i;
     uint32_t test_rate;
     int result = PASS;
     int32_t fd = 0;
     /* Tests rtc_open */
     if (rtc_open(0) == -1) {printf("RTC failed to open!\n"); result = FAIL;}
     /* Tests ability to set all possbile user defined RTC freqeuncies */
     for (i = 2; i <= 512; i = i * 2) {
         test_rate = i;
         if (rtc_write(fd, (void*)&test_rate, 4) != 4) {
             printf("RTC failed to set rate to %dHz!\n", test_rate);
             result = FAIL;
         }
     }
     /* Tests if a non power of two frequency returns an error */
     test_rate = 157;
     if (rtc_write(fd, (void*)&test_rate, 4) == 4) {
         printf("RTC allowed a non-power of two frequency call!\n");
         result = FAIL;
     }
     /* Tests if user attempting to set a frequency above 1024Hz returns an error */
     test_rate = 2048;
     if (rtc_write(fd, (void*)&test_rate, 4) == 4) {
         printf("RTC allowed user to set a frequency greater than 1024Hz!\n");
         result = FAIL;
     }
     /*  !!! Uncomment to see a visual indication of frequencies of the RTC !!! */
     printf("Setting frequency to 4Hz and printing ten numbers...\n");
     test_rate = 4;
     rtc_write(fd, (void*)&test_rate, 4);
     for (i = 0; i <= 9; i++) {
         rtc_read(fd, &test_rate, 1);
         printf("%d ", i);
     } printf("\n");
     /* Tests if RTC closes properly */
     if (rtc_close(fd)) {printf("RTC failed to close!\n"); result = FAIL;}
     return result;
 }
terminal_test()
int terminal_test ()
Definition at line 132 of file tests.c.
References PASS, printf(), terminal_read(), terminal_write(), TEST_HEADER, and TEST_STR_LENGTH.
Referenced by launch_tests().
                    {
     TEST_HEADER;
     int result = PASS;
     char password[TEST_STR_LENGTH];
     printf("Term Test: Give me your password!!:\n");
     int len = terminal_read(password, TEST_STR_LENGTH);
     printf("Yum. %d characters. Nice length.\nYour password is:", len);
     terminal_write(password, len);
     printf("\n Moving to next test. \n");
     return result;
 }