HoneyIllinix 391 MP 3: tests.h File Reference
tests.h File Reference
Functions
void launch_tests ()
Function Documentation
launch_tests()
void launch_tests ()
Definition at line 205 of file tests.c.
References exception_test(), idt_test(), paging_tests(), printf(), rtc_test(), terminal_test(), and TEST_OUTPUT.
Referenced by entry().
                    {
     printf("### RUNNING TEST SUITE ###\n");
     printf("Beginning checkpoint 1 tests...\n");
     TEST_OUTPUT("idt_test", idt_test());
     TEST_OUTPUT("rtc_test", rtc_test());
     TEST_OUTPUT("terminal_test", terminal_test());
     TEST_OUTPUT("paging_tests", paging_tests());  // this is going to crash machine, put any tests before this
     TEST_OUTPUT("exception_test", exception_test()); // this is going to crash machine, put any tests before this
     printf("checkpoint 1 tests done.\n");
 }